### PR TITLE
[WIP] use SafariViewController if available

### PR DESCRIPTION
**Pull request by TETRA2000**
please merge #37 first

**known problem**
* top area is hidden on scroll

simulator screen shot dec 23 2015 17 22 28

### CODE REVIEW

**Comment by Dimillian** [comment]
Thanks a lot :D 
Could you rebase this pull request on master ? 
I finished the Swift 2 conversion + Fixed a ton of other things. 

I really think a SafariViewController is far better, so we'll go forward with this.

**Comment by TETRA2000** [comment]
I merged master.

Thanks for a comment.
I'm glad to hear that you have same idea !!

And thank you for fixing my last PR.

**Comment by Dimillian** [comment]
Question: 
I'm not sure yet, do we use `showViewController` or we switch to `presentViewController(SafariViewController(URL: url), animated: true, completion: nil)` to get the top URL bar (and loose the orange) ? 

screen shot 2015-12-23 at 10 51 02

**Comment by TETRA2000** [comment]
`presentViewController ` seems to work fine !

I also changed to override status bar color in last commit.
I tried to fix nav bar color but couldn't.

I think this is better solution if you don't mind design.

**Comment by TETRA2000** [comment]
thanks!!

**Pull request merged**
